version: '3'

services:
  movie-api:
    image: movie-api:1.0
    build: ./movie-api
    environment:
      MONGODB_USER: ${MONGODB_USER}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_NAME: ${DATABASE_NAME}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - 3000:3000
  movie-page:
    image: movie-page:1.0
    build: ./movie-page
    ports:
      - 80:80
    links:
      - movie-api
